// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using try4.data;

#nullable disable

namespace try4.Migrations
{
    [DbContext(typeof(MyDbContext))]
    [Migration("20260413135750_try")]
    partial class @try
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("try4.Models.Center", b =>
                {
                    b.Property<int>("CenterId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CenterId"));

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int?>("OrderIndex")
                        .HasColumnType("int");

                    b.HasKey("CenterId");

                    b.ToTable("Centers");
                });

            modelBuilder.Entity("try4.Models.Rout", b =>
                {
                    b.Property<int>("RouteId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("RouteId"));

                    b.Property<int>("CenterAid")
                        .HasColumnType("int")
                        .HasColumnName("CenterAId");

                    b.Property<int>("CenterBid")
                        .HasColumnType("int")
                        .HasColumnName("CenterBId");

                    b.Property<int>("DurationMinutes")
                        .HasColumnType("int");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<int>("MaxCenterId")
                        .HasColumnType("int");

                    b.Property<int>("MinCenterId")
                        .HasColumnType("int");

                    b.HasKey("RouteId");

                    b.HasIndex("CenterAid");

                    b.HasIndex("CenterBid");

                    b.ToTable("Routs");
                });

            modelBuilder.Entity("try4.Models.Trip", b =>
                {
                    b.Property<int>("TripId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("TripId"));

                    b.Property<int>("BookedSeats")
                        .HasColumnType("int");

                    b.Property<DateTime?>("DepartureDate")
                        .HasColumnType("datetime2");

                    b.Property<TimeOnly>("DepartureTime")
                        .HasColumnType("time");

                    b.Property<int>("FromCenterId")
                        .HasColumnType("int");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<int>("RouteId")
                        .HasColumnType("int");

                    b.Property<int>("ToCenterId")
                        .HasColumnType("int");

                    b.Property<int>("TotalSeats")
                        .HasColumnType("int");

                    b.Property<double>("TripPrice")
                        .HasColumnType("float");

                    b.HasKey("TripId");

                    b.HasIndex("FromCenterId");

                    b.HasIndex("RouteId");

                    b.HasIndex("ToCenterId");

                    b.ToTable("Trips");
                });

            modelBuilder.Entity("try4.Models.Rout", b =>
                {
                    b.HasOne("try4.Models.Center", "CenterA")
                        .WithMany("RouteCenterAs")
                        .HasForeignKey("CenterAid")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("try4.Models.Center", "CenterB")
                        .WithMany("RouteCenterBs")
                        .HasForeignKey("CenterBid")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("CenterA");

                    b.Navigation("CenterB");
                });

            modelBuilder.Entity("try4.Models.Trip", b =>
                {
                    b.HasOne("try4.Models.Center", "FromCenter")
                        .WithMany("TripFromCenters")
                        .HasForeignKey("FromCenterId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("try4.Models.Rout", "Rout")
                        .WithMany("Trips")
                        .HasForeignKey("RouteId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("try4.Models.Center", "ToCenter")
                        .WithMany("TripToCenters")
                        .HasForeignKey("ToCenterId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("FromCenter");

                    b.Navigation("Rout");

                    b.Navigation("ToCenter");
                });

            modelBuilder.Entity("try4.Models.Center", b =>
                {
                    b.Navigation("RouteCenterAs");

                    b.Navigation("RouteCenterBs");

                    b.Navigation("TripFromCenters");

                    b.Navigation("TripToCenters");
                });

            modelBuilder.Entity("try4.Models.Rout", b =>
                {
                    b.Navigation("Trips");
                });
#pragma warning restore 612, 618
        }
    }
}
